config/routes.rb
SampleApp::Application.routes.draw do
  
  get "relationships/create"
  get "relationships/destroy"
  resources :users do
    member do
      get :following, :followers
    end 
  end

  get "microposts/create"
  get "microposts/destroy"
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  get "users/new"

  root 'static_pages#home'
  match "/signin", to: "sessions#new", via: 'get'
  match "/signout", to: "sessions#destroy", via: 'delete'
  match "/signup", to: "users#new", via: 'get'
  match "/help", to: "static_pages#help", via: 'get'
  match "/about", to: "static_pages#about", via: 'get'
  match "/contact", to: "static_pages#contact", via: 'get'

 
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
		@micropost = current_user.microposts.build
		@feed_items = current_user.feed.paginate(page: params[:page])
	end
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>
<p>This is an example of an about page.</p>
	

app/views/static_pages/contact.html.erb
<%provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>
<p>This is an example of a contact us page.</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>This is an example of a Help page.</p>
	

app/views/static_pages/home.html.erb
<% #provide(:title, 'Home') %>
<% if signed_in? %>
	<div class = "row">
		<aside class = "span4">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/stats' %>
			</section>
			<section>
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
		<div class ="span8">
			<h3>Micropost Feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
<% else %>

<div class="center hero-unit">
  <h1>Welcome to Fake Tweet</h1>
<h2>
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
<%#= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

<% end %>