config/routes.rb
SampleApp::Application.routes.draw do
  
  get "relationships/create"
  get "relationships/destroy"
  resources :users do
    member do
      get :following, :followers
    end 
  end

  get "microposts/create"
  get "microposts/destroy"
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  get "users/new"

  root 'static_pages#home'
  match "/signin", to: "sessions#new", via: 'get'
  match "/signout", to: "sessions#destroy", via: 'delete'
  match "/signup", to: "users#new", via: 'get'
  match "/help", to: "static_pages#help", via: 'get'
  match "/about", to: "static_pages#about", via: 'get'
  match "/contact", to: "static_pages#contact", via: 'get'

 
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
	<a href="google.com">Faketweet</a>
	by Colton Seal
	
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
	</footer>

app/views/layouts/_header.html.erb
<script type="text/javascript">  <!--This needs to be added to get the dropdown menu to work -->
    $(document).ready(function () {
        $('.dropdown-toggle').dropdown();
    });
</script>
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Fake Tweet", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Users", users_path %> </li>
						<li class = "dropdown">
							<a href="#" class = "dropdown-toggle" data_toggle = "dropdown">
								Account <b class = "caret"></b>
							</a>
							<ul class="dropdown-menu" role = "menu" aria-labelledby="dLabel">
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings",edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li>
									<%= link_to "Sign out", signout_path, method: "delete" %>
								</li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %> 
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%#= render 'layouts/shim' %> 
  </head>
  <body>
    <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |key, value| %>
        <div class = "alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %> 
    <%= render 'layouts/footer' %> 
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>